name: nr.pylang.bundle
version: 0.0.1
description: Create standalone Python applications.
requirements:
- python ^2.7|^3.4
- distlib ^0.2.7
- nr.databind.core ~0.0.1
- nr.fs ^1.3.1
- nr.sumtype ^0.0.1
- nr.stream ^0.0.1
- tqdm ^4.42.1
entrypoints:
  console_scripts:
  - nr-pylang-bundle = nr.pylang.bundle.__main__:_entrypoint_main
