name: nr.pylang.bundle
version: 0.0.1
description: Create standalone Python applications.
requirements:
- python ^3.6
- dataclasses
- distlib ^0.2.7
- nr.fs ^1.3.1
- nr.stream ^0.1.1
- nr.pylang.utils ^0.1.0
- tqdm ^4.42.1
entrypoints:
  console_scripts:
  - nr-pylang-bundle = nr.pylang.bundle.__main__:_entrypoint_main
