name: nr.databind.json
version: "0.0.6"
description: Deserialize JSON into Python objects and reverse.
requirements:
  - python ^2.7|^3.4
  - nr.collections ^0.0.1
  - nr.databind.core ~0.0.1
  - nr.interface ~0.0.1
  - nr.parsing.date ~0.1.0
  - nr.pylang.utils ~0.0.1
  - test:
    - pytest
    - PyYAML
