---
kind: pipeline
type: docker
name: python-3.6
steps:

  - name: test-all
    image: python:3.6
    environment:
      PYTHON_PIP: pip
      VIRTUALENV: python -m venv
    commands:
      - pip install shut==0.10.0 -q
      - shut mono test --isolate

---
kind: pipeline
type: docker
name: python-3.9
steps:

  - name: test-all
    image: python:3.9
    environment:
      PYTHON_PIP: pip
      VIRTUALENV: python -m venv
    commands:
      - pip install shut==0.10.0 -q
      - shut mono test --isolate
