{% set data = load_setup_py_data() %}

package:
  name: nr.types
  version: {{ data.get('version') }}

source:
  path: .

build:
  noarch: python
  script: "python -m pip install . --no-deps --ignore-installed -vv"
  include_recipe: false

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six >=1.11.0

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: {{ data.get('license') }}
  license_file: LICENSE.txt
  summary: {{ data.get('description') }}
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - nrosenstein
