# This file was auto-generated by Shut. DO NOT EDIT
# For more information about Shut, check out https://pypi.org/project/shut/

from __future__ import print_function
import io
import os
import setuptools
import sys

requirements = [
  'nr.collections >=0.0.1,<1.0.0',
  'nr.metaclass >=0.0.1,<0.1.0',
  'nr.pylang.utils >=0.0.1,<0.1.0',
  'six >=1.11.0,<2.0.0',
]
test_requirements = [
  'pytest',
]

setuptools.setup(
  name = 'nr.interface',
  version = '0.0.3',
  author = 'Niklas Rosenstein',
  author_email = 'rosensteinniklas@gmail.com',
  description = 'Interface definitions for Python.',
  long_description = None,
  long_description_content_type = None,
  url = 'https://git.niklasrosenstein.com/NiklasRosenstein/nr',
  license = 'MIT',
  py_modules = ['nr.interface'],
  package_dir = {'': 'src'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = {},
  tests_require = test_requirements,
  python_requires = None,  # '>=2.6,<3.0.0|>=3.4,<4.0.0',
  data_files = [],
  entry_points = {},
  cmdclass = {},
  keywords = [],
  classifiers = [],
  zip_safe = True,
  options = {
    'bdist_wheel': {
      'universal': True,
    },
  },
)
