name: "nr.concurrency"
version: "0.0.1"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "Library for concurrency in Python."
requirements:
  - python ^3.4
  - nr.interface ~0.0.2
