name: "nr.algo.graph"
version: "0.1.0"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "Package description here."
requirements:
- python ^3.4
- nr.interface ~0.0.1
