name: nr.collections
version: 1.0.0
description: Useful container datatypes (ChainDict and OrderedSet).
requirements:
- python ^3.6
test-requirements:
- nr.fs ^1.5.0
- pytest
test-drivers:
- type: pytest
