# This file was auto-generated by Shut. DO NOT EDIT
# For more information about Shut, check out https://pypi.org/project/shut/

from __future__ import print_function
import io
import os
import setuptools
import sys

requirements = []

setuptools.setup(
  name = 'nr.proxy',
  version = '1.0.0',
  author = 'Niklas Rosenstein',
  author_email = 'rosensteinniklas@gmail.com',
  description = 'Provides proxy classes that allow accessing objects that are usually only accessible via function calls as objects directly.',
  long_description = None,
  long_description_content_type = None,
  url = 'https://git.niklasrosenstein.com/NiklasRosenstein/nr/src/branch/develop/nr.proxy',
  license = 'MIT',
  py_modules = ['nr.proxy'],
  package_dir = {'': 'src'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = {},
  tests_require = [],
  python_requires = '>=3.5.0,<4.0.0',
  data_files = [],
  entry_points = {},
  cmdclass = {},
  keywords = [],
  classifiers = [],
  zip_safe = True,
)
