name: "nr.ansiterm"
version: "0.0.1"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "Package description here."
requirements:
  - python ^3.5
  - nr.pylang.utils ~0.0.2
