package:
  name: nr.commons
  version: "0.0.1"
  description: |
    Provides common utilities that didn't make it into any of the other
    nr namespace packages.

requirements:
  - test: [nr.collections ^0.1.0]
