name: nr.config
version: 0.1.1
description: Utility library to implement composable YAML configuration files.
typed: true
requirements:
- python ^3.4
- nr.collections ^0.1.1
- nr.pylang.utils ^0.0.4
- six ^1.14.0
- Jinja2 ^2.11.2
test-requirements:
- pytest
- PyYAML
- nr.fs ^1.6.0
- watchdog
extra-requirements:
  reloader:
  - watchdog ~0.10.2
test-driver:
  type: pytest
