name: "nr.config"
version: "0.0.6"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "Package description here."
requirements:
- python ^3.4
- nr.collections ^0.0.1
- nr.pylang.utils ~0.0.1
- six ^1.14.0
- test:
  - pytest
  - PyYAML
  - nr.fs ^1.6.0
- extra:
    reloader:
    - watchdog ~0.10.2
