name: "nr.config"
version: "0.0.2"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "Package description here."
requirements:
  - python ^3.4
  - nr.collections ^0.0.1
  - six ^1.14.0
  - watchdog ~0.10.2
