name: "nr.pylang.utils"
version: "0.0.3"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "Package description here."
requirements:
- python ^3.4
- nr.collections ^0.0.1
test-requirements:
- pytest
test-driver: {type: pytest}
