name: nr.utils.wsgi
version: 0.1.0
description: Package description here.
requirements:
- python ^3.4
- nr.databind.core ~0.0.15
- nr.databind.core ~0.0.9
- nr.interface ~0.0.2
- nr.utils.process ~0.0.4
entrypoints:
  nr.utils.wsgi.IWsgiRunner:
  - flask = nr.utils.wsgi:FlaskRunner
  - gunicorn = nr.utils.wsgi:GunicornRunner
typed: false
