package:
  name: nr.databind
  description: Bind structured data directly to typed objects.
  license: MIT

requirements:
  python: ^2.7|^3.4
  test:
    - pytest
    - PyYAML

publish:
  - layout: pypi
