package:
  name: nr.databind
  version: 0.1.0
  description: Bind structured data directly to typed objects.

requirements:
  - python ^2.7|^3.4
  - nr.interface ~0.1.0
  - nr.parsing.date ~0.1.0
  - nr.stream ~0.1.0
  - test:
    - pytest
    - PyYAML

entrypoints:
  nr.databind.core.struct.Mixin:
    - json = nr.databind.json:JsonMixin
    - tuple = nr.databind.contrib.mixins.tuple:TupleMixin
