package:
  name: nr.databind
  version: 0.9.0
  description: Bind structured data directly to typed objects.

requirements:
  - python ^2.7|^3.4
  - nr.interface ^1.0.0
  - test:
    - pytest
    - PyYAML
