name: "nr.utils.re"
version: "0.1.0"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "This module provides some utility functions for applying regular expressions."
requirements:
- python ^2.7|^3.4
test-requirements:
- pytest
