name: nr.parsing.date
version: "0.0.2"
description: |
  A simple and fast date parsing library. Uses dateutil for timezone
  offset support.
requirements:
  - python ^2.7|^3.4
  - test:
    - python-dateutil
