name: nr.parsing.date
version: 0.6.1
description: A fast, regular-expression based library for parsing dates, plus support for ISO 8601 durations.
license: MIT
requirements:
- python ^3.6
- nr.utils.re ^0.2.0
test-requirements:
- pandas
- pytest
test-driver:
  type: pytest
typed: true
