package:
  name: nr.parsing.date
  version: 0.9.0
  description: |
    A simple and fast date parsing library. Uses dateutil for timezone
    offset support.

requirements:
  - python ^2.7|^3.4
  - python-dateutil
